{
 "title": "Public nodes uptime",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(probe_success, network)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Query timings",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{type=~\"api|rpc\"}",
     "legendFormat": "{{type}} {{network }}"
    }
   ]
  },
  { "title": "$network stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "network" },
  {
   "title": "status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{network=\"$network\",type=\"rpc\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{network=\"$network\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Historical uptime",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "probe_success{network=\"$network\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "SSL expiration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{network=\"$network\",type=\"rpc\"} - time()",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "30 days uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "    sum(sum_over_time(probe_success{network=\"$network\",type=\"rpc\"}[30d]))\n/\n    sum(count_over_time(probe_success{network=\"$network\",type=\"rpc\"}[30d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average query time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{network=\"$network\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average DNS lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{network=\"$network\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}