---
- name: Install Alertmanager
  hosts: "{{ hosts | default('monitoring')  }}"

  vars:
    alertmanager_tar_file: /tmp/alertmanager.tar.gz
    alertmanager_tmp_path: /tmp/alertmanager
    alertmanager_config_path: /etc/alertmanager

  tasks:
    - name: Get latest release
      ansible.builtin.uri:
        url: https://api.github.com/repos/prometheus/alertmanager/releases/latest
        return_content: true
      register: release_info

    - name: Get latest release JSON
      ansible.builtin.set_fact:
        release_info_json: "{{ release_info.content | from_json }}"

    - name: Set Alertmanager version to {{ release_info_json.tag_name[1:] }}
      ansible.builtin.set_fact:
        version: "{{ release_info_json.tag_name[1:] }}"

    - name: Download Alertmanager binary to local folder
      ansible.builtin.get_url:
        url: https://github.com/prometheus/alertmanager/releases/download/v{{ version }}/alertmanager-{{ version }}.linux-amd64.tar.gz
        dest: "{{ alertmanager_tar_file }}"
        mode: '0755'

    - name: Create Alertmanager tmp directory if it does not exist
      ansible.builtin.file:
        path: "{{ alertmanager_tmp_path }}"
        state: directory
        mode: '0755'

    - name: Unzip Alertmanager
      ansible.builtin.unarchive:
        src: "{{ alertmanager_tar_file }}"
        dest: "{{ alertmanager_tmp_path }}"
        remote_src: true
        mode: '0755'

    - name: Copy Alertmanager binary
      become: true
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /usr/bin
        mode: '0755'
        remote_src: true
      loop:
        - "{{ alertmanager_tmp_path }}/alertmanager-{{ version }}.linux-amd64/alertmanager"
        - "{{ alertmanager_tmp_path }}/alertmanager-{{ version }}.linux-amd64/amtool"

    - name: Create alertmanager group
      become: true
      ansible.builtin.group:
        name: alertmanager
        state: present

    - name: Add alertmanager user
      ansible.builtin.user:
        name: alertmanager
        groups: alertmanager
        shell: /sbin/nologin
        create_home: false
        append: true
        state: present
      become: true

    - name: Create Alertmanager folders
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
        group: alertmanager
        owner: alertmanager
      loop:
        - /etc/alertmanager
        - /var/lib/alertmanager

    - name: Set up Alertmanager config
      become: true
      ansible.builtin.copy:
        src: ../../configs/alertmanager
        dest: /etc
        mode: '0755'

    - name: Put basic auth config
      become: true
      when: alertmanager_username is defined and alertmanager_password is defined
      ansible.builtin.template:
        src: ../../../templates/monitoring/alertmanager.web.yml.j2
        dest: /etc/alertmanager/web.yml
        mode: '0755'

    - name: Set up Alertmanager systemd config
      become: true
      ansible.builtin.template:
        src: ../../../templates/monitoring/alertmanager.service.j2
        dest: /etc/systemd/system/alertmanager.service
        mode: '0644'

    - name: Start Alertmanager and enable it on autostart
      become: true
      ansible.builtin.service:
        name: alertmanager
        state: restarted
        enabled: true
