---
- name: Install Grafana
  hosts: "{{ hosts | default('monitoring')  }}"

  tasks:
    - name: Install required packages
      become: true
      ansible.builtin.package:
        name:
          - apt-transport-https
          - software-properties-common
          - wget
        state: present

    # Taken from here: https://grafana.com/docs/grafana/latest/setup-grafana/image-rendering/troubleshooting/
    - name: Install grafana-image-renderer dependencies
      become: true
      ansible.builtin.package:
        name:
          - libx11-6
          - libx11-xcb1
          - libxcomposite1
          - libxcursor1
          - libxdamage1
          - libxext6
          - libxfixes3
          - libxi6
          - libxrender1
          - libxtst6
          - libglib2.0-0
          - libnss3
          - libcups2
          - libdbus-1-3
          - libxss1
          - libxrandr2
          - libgtk-3-0
          - libasound2
          - libxcb-dri3-0
          - libgbm1
          - libxshmfence1
        state: present

    - name: Creates keyring directory
      become: true
      ansible.builtin.file:
        path: /etc/apt/keyrings/
        state: directory
        mode: '0644'

    - name: Download repository GPG
      become: true
      ansible.builtin.shell: "wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/grafana.gpg > /dev/null" # noqa: command-instead-of-module risky-shell-pipe
      args:
        executable: /bin/bash
      changed_when: true

    - name: Add apt entry
      become: true
      ansible.builtin.copy:
        content: 'deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main'
        dest: /etc/apt/sources.list.d/grafana.list
        mode: '0644'

    - name: Update package cache
      become: true
      ansible.builtin.package:
        update_cache: true

    - name: Install Grafana
      become: true
      ansible.builtin.package:
        name: grafana
        state: present

    - name: Install grafana-image-renderer plugin
      become: true
      ansible.builtin.shell: "grafana-cli plugins install grafana-image-renderer"
      args:
        executable: /bin/bash
      changed_when: true

    - name: Set Grafana URL
      become: true
      when: grafana_domain is defined
      community.general.ini_file:
        path: /etc/grafana/grafana.ini
        section: server
        option: root_url
        value: '"{{ grafana_domain }}"'
        mode: '0644'

    - name: Start Grafana and enable it on autostart
      become: true
      ansible.builtin.service:
        name: grafana-server
        state: restarted
        enabled: true
