{
 "title": "cosmos-transactions-bot",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": {
     "query": "label_values(cosmos_transactions_bot_node_reports,chain)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "app version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_transactions_bot_version",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "nodes connected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_transactions_bot_node_connected == 1)",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "nodes errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_transactions_bot_node_connected == 0) OR on() vector(0)",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "reporters enabled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_transactions_bot_reporter_enabled == 1) OR on() vector(0)",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "total reports sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cosmos_transactions_bot_node_reports)",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "time since latest block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - missed_blocks_checker_last_time",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "reports sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(cosmos_transactions_bot_events_matched{chain=\"$chain\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "report entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(cosmos_transactions_bot_node_report_entries_total{chain=\"$chain\"}[$__rate_interval])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "WS events received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(cosmos_transactions_bot_events_total{chain=\"$chain\"}[$__rate_interval])",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "WS events total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(cosmos_transactions_bot_events_total{chain=\"$chain\"}[$__rate_interval])) by (chain)",
     "legendFormat": "{{chain }}"
    }
   ]
  },
  {
   "title": "WS events filtered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(cosmos_transactions_bot_events_filtered{chain=\"$chain\"}[$__rate_interval])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "WS events matched",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(cosmos_transactions_bot_events_matched{chain=\"$chain\"}[$__rate_interval])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "successful queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(cosmos_transactions_bot_node_successful_queries_total{chain=\"$chain\"}[$__rate_interval])) by (type, node)",
     "legendFormat": "{{ type }} {{node}}"
    }
   ]
  },
  {
   "title": "failed queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(cosmos_transactions_bot_node_node_failed_queries_total{chain=\"$chain\"}[$__rate_interval])) by (type, node)",
     "legendFormat": "{{ type }} {{node}}"
    }
   ]
  },
  {
   "title": "node reconnects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(cosmos_transactions_bot_reconnects_total{chain=\"$chain\"}[$__rate_interval])",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "app logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{systemd_unit=\"cosmos-transactions-bot.service\", host=\"monitoring-logging\"}"
    }
   ]
  }
 ]
}