{
 "title": "Hermes",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Is Hermes active?", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "broadcast_errors_total over 1 minute",
   "type": "timeseries",
   "description": "Indicates how many acknowledgements were processed by the relayer. It can be used with `acknowledgment_events` as every event should be processed by Hermes.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(broadcast_errors_total[$__rate_interval]) > 0",
     "legendFormat": "{{account}}: {{ error_code }}: {{ error_description }}"
    }
   ]
  },
  {
   "title": "messages_submitted over 1 minute",
   "type": "timeseries",
   "description": "Indicates if Hermes is submitting messages to a specific chain ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(messages_submitted_total[1m])",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Wallet balances",
   "type": "timeseries",
   "description": "Indicates if you have enough funds on your wallet. Hermes can not relay without spending gas. Thus, it is important to set alarms which monitor the gas.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "wallet_balance / 1000000", "legendFormat": "{{chain}}: {{account}}" }
   ]
  },
  {
   "title": "client_updates_submitted over 1 minute",
   "type": "timeseries",
   "description": "Indicates if clients are getting updated.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(client_updates_submitted_total[1m]) > 0",
     "legendFormat": "{{src_chain}} -> {{dst_chain}}:{{client}}"
    }
   ]
  },
  {
   "title": "Gas variation over 1 minute",
   "type": "timeseries",
   "description": "Indicates if you are spending gas and how much you are spending.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "rate(wallet_balance[1m]) > 0", "legendFormat": "{{chain}}: {{account}}" }
   ]
  },
  {
   "title": "Current number of workers",
   "type": "timeseries",
   "description": "This panel indicates which type of workers are active for every instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "workers", "legendFormat": "{{type}}" }
   ]
  },
  { "title": "Are transactions successful?", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Oldest pending packets",
   "type": "table",
   "description": "Represents the sequence number and the date of the oldest pending packet. Use this metric to identify stuck packets.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "backlog_oldest_sequence",
     "legendFormat": "{{chain}}:{{channel}}/{{port}}-{{counterparty}} ({{instance}})"
    },
    {
     "expr": "backlog_latest_update_timestamp * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending packet per path",
   "type": "timeseries",
   "description": "Indicates how many packets are being processed by Hermes. If this value stays constantly more than 0, it could mean that a packet is stuck.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "backlog_size > 0",
     "legendFormat": "{{chain}}:{{channel}}/{{port}}-{{counterparty}}"
    }
   ]
  },
  {
   "title": "receive_packets_confirmed over 1 minute",
   "type": "timeseries",
   "description": "Indicates how many `receive_packets` were processed by Hermes. It can be used with `send_packet_events` as every `send_packet_event` should trigger the processing of a `receive_packet`.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "expr": "delta(receive_packets_confirmed_total[1m]) > 0",
     "legendFormat": "{{src_chain}}:{{src_channel}}/{{src_port}}"
    }
   ]
  },
  {
   "title": "95th quantile of tx_latency_confirmed rate over 5 minutes",
   "type": "timeseries",
   "description": "Indicates the latency rate for all transactions confirmed by each chain.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, chain) (rate(tx_latency_confirmed_bucket[5m])))",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "timeout_packets_confirmed over 1 minute",
   "type": "timeseries",
   "description": "Indicates how many `timeout_packets` were processed by the relayer. It can be used with `timeout_packet_events` as every `timeout_event` should be processed by Hermes.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "delta(timeout_packets_confirmed_total[1m]) > 0",
     "legendFormat": "{{src_chain}}:{{src_channel}}/{{src_port}}"
    }
   ]
  },
  {
   "title": "acknowledgment_packets_confirmed over 1 minute",
   "type": "timeseries",
   "description": "Indicates how many acknowledgements were processed by the relayer. It can be used with `acknowledgment_events` as every event should be processed by Hermes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "rate(acknowledgment_packets_confirmed_total[1m]) > 0",
     "legendFormat": "{{src_chain}} -> {{ dst_chain }} :{{src_channel}}/{{src_port}}"
    }
   ]
  },
  {
   "title": "What is the overall IBC status of each network?",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 }
  },
  {
   "title": "send_packets_events over 1 minute",
   "type": "timeseries",
   "description": "Indicates the number of  `send_packet_event` observed.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "rate(send_packet_events_total[1m]) > 0",
     "legendFormat": "{{chain}}:{{channel}}/{{port}}-{{counterparty}}"
    }
   ]
  },
  {
   "title": "acknowledgement_events over 1 minute",
   "type": "timeseries",
   "description": "Indicates the number of  `acknowledgement_event` observed.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
   "targets": [
    {
     "expr": "rate(acknowledgement_events_total[1m]) > 0",
     "legendFormat": "{{chain}}:{{channel}}/{{port}}-{{counterparty}}"
    }
   ]
  },
  {
   "title": "timeout_events over 1 minute",
   "type": "timeseries",
   "description": "Indicates the number of  `timeout_event` observed.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
   "targets": [
    {
     "expr": "rate(timeout_events_total[1m]) > 0",
     "legendFormat": "{{chain}}:{{channel}}/{{port}}-{{counterparty}}"
    }
   ]
  },
  {
   "title": "ws_events received over 1 minute",
   "type": "timeseries",
   "description": "Indicates the number of  `event` observed via the websocket subcription.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
   "targets": [
    { "expr": "rate(ws_events_total[1m])", "legendFormat": "{{chain}}" }
   ]
  },
  {
   "title": "ws_reconnect over 1 minute",
   "type": "timeseries",
   "description": "Indicates the number of times Hermes reconnected to the websocket.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 63 },
   "targets": [
    { "expr": "rate(ws_reconnect_total[1m])", "legendFormat": "{{chain}}" }
   ]
  },
  {
   "title": "RPC queries sent over 1 minute",
   "type": "timeseries",
   "description": "Indicate the number of queries per instance and chain.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 63 },
   "targets": [
    {
     "expr": "sum(rate(queries_total[1m])) by(chain)",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "How efficient and how secure is the IBC status on each network?",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 }
  },
  {
   "title": "cleared_acknowledgment_events over 1 minute",
   "type": "timeseries",
   "description": "Cleared `acknowledgment_events` rate per path. It is an indication that IBC packet relaying may be unsuccessful and that Hermes periodically finds packets to clear (i.e., unblock).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "rate(cleared_acknowledgment_events_total[1m]) > 0",
     "legendFormat": "{{chain}}:{{channel}}/{{port}}-{{counterparty}}"
    }
   ]
  },
  {
   "title": "cleared_send_packet_events over 1 minute",
   "type": "timeseries",
   "description": "Cleared `send_packet_events` rate per path. It is an indication that IBC packet relaying may be unsuccessful and that Hermes periodically finds packets to clear (i.e., unblock).",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "rate(cleared_send_packet_events_total[1m]) > 0",
     "legendFormat": "{{chain}}:{{channel}}/{{port}}-{{counterparty}}"
    }
   ]
  },
  {
   "title": "95th quantile of tx_latency_submitted rate over 5 minutes",
   "type": "timeseries",
   "description": "Indicates the latency rate for all transactions submitted to each chain.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, chain, instance) (rate(tx_latency_submitted_bucket[5m])))",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "queries_cache_hits over 1 minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "sum by(chain) (rate(queries_cache_hits_total[1m]))",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "tx_latency_submitted histogram ibc-0",
   "type": "bargauge",
   "description": "Indicates the latency rate for all transactions submitted from ibc-0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(tx_latency_submitted_bucket{chain=\"ibc-0\"}[$__range])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "tx_latency_confirmed_bucket histogram ibc-0",
   "type": "bargauge",
   "description": "Indicates the latency rate for all transactions confirmed from ibc-0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(tx_latency_confirmed_bucket{chain=\"ibc-0\"}[$__range])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "client_misbehaviours_submitted over 5 minutes",
   "type": "timeseries",
   "description": "If `misbehaviour = true` then hermes will detect misbehaviours from clients and stop relaying to this client if one is detected. It is possible to set an alarm on this. ",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "rate(client_misbehaviours_submitted_total[5m])",
     "legendFormat": "{{src_chain}}-{{dst_chain}}:{{client}}"
    }
   ]
  },
  { "title": "Extra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "Hermes logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "{systemd_unit=\"hermes.service\"} |= ``"
    }
   ]
  }
 ]
}