{
 "title": "missed-blocks-checker",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": {
     "query": "label_values(missed_blocks_checker_node_reports,chain)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "app version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "missed_blocks_checker_version", "legendFormat": "{{chain}}" }
   ]
  },
  {
   "title": "nodes connected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(missed_blocks_checker_node_connected{chain=\"$chain\"} == 1)",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "nodes errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(missed_blocks_checker_node_connected{chain=\"$chain\"} == 0) OR on() vector(0)",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "reporters enabled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(missed_blocks_checker_reporter_enabled{chain=\"$chain\"} == 1) OR on() vector(0)",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "total reports sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(missed_blocks_checker_node_reports{chain=\"$chain\"})",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "active validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(missed_blocks_checker_active{chain=\"$chain\"})",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "jailed validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(missed_blocks_checker_jailed{chain=\"$chain\"})",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "tombstoned validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(missed_blocks_checker_tombstoned{chain=\"$chain\"})",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "time since latest block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - missed_blocks_checker_last_time",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "reports sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(missed_blocks_checker_node_reports{chain=\"$chain\"}[$__rate_interval])",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "report entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(missed_blocks_checker_node_report_entries_total{chain=\"$chain\"}[$__rate_interval])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "successful queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(missed_blocks_checker_node_successful_queries_total{chain=\"$chain\"}[$__rate_interval])) by (type, node)",
     "legendFormat": "{{ type }} {{node}}"
    }
   ]
  },
  {
   "title": "failed queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(missed_blocks_checker_node_failed_queries_total{chain=\"$chain\"}[$__rate_interval])) by (node, type)",
     "legendFormat": "{{ type }} {{node}}"
    }
   ]
  },
  {
   "title": "WS events received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(missed_blocks_checker_events_total{chain=\"$chain\"}[$__rate_interval])",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "node reconnects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(missed_blocks_checker_reconnects_total{chain=\"$chain\"}[$__rate_interval])",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "missed blocks counter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(missed_blocks_checker_missed_blocks{chain=\"$chain\"}) AND (missed_blocks_checker_active{chain=\"$chain\"} == 1)",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "active blocks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "missed_blocks_checker_active_blocks{chain=\"$chain\"} > 0",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "missing blocks in memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "missed_blocks_checker_store_blocks - missed_blocks_checker_node_blocks",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "{systemd_unit=\"missed-blocks-checker.service\", host=\"monitoring-logging\"}"
    }
   ]
  }
 ]
}