{
 "title": "rly",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "query errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(cosmos_relayer_block_query_errors_total[$__rate_interval]) > 0",
     "legendFormat": "{{ chain }}@{{ type }}"
    }
   ]
  },
  {
   "title": "latest block delta",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(cosmos_relayer_chain_latest_height[5m])",
     "legendFormat": "{{ chain }}"
    }
   ]
  },
  {
   "title": "relayed packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "rate(cosmos_relayer_relayed_packets_total[$__rate_interval]) > 0",
     "legendFormat": "{{ type }}@{{ chain }} -> {{ path_name }}"
    }
   ]
  },
  {
   "title": "unrelayed acks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "cosmos_relayer_unrelayed_acks > 0",
     "legendFormat": "{{ src_chain }} -> {{ dest_chain }}"
    }
   ]
  },
  {
   "title": "unrelayed packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "cosmos_relayer_unrelayed_packets > 0",
     "legendFormat": "{{ src_chain }} -> {{ dest_chain }}"
    }
   ]
  },
  {
   "title": "wallet balance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "cosmos_relayer_wallet_balance",
     "legendFormat": "{{ chain }}, {{ denom }}: price: {{ gas_price}}"
    }
   ]
  },
  {
   "title": "client expiration",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cosmos_relayer_client_expiration_seconds",
     "legendFormat": "{{ chain }}@{{ path_name }}"
    }
   ]
  },
  {
   "title": "tx errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "rate(cosmos_relayer_tx_errors_total[$__rate_interval]) > 0",
     "legendFormat": "{{ chain }}@{{ path_name }}: {{ cause }}"
    }
   ]
  }
 ]
}