{
 "title": "balances",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "restake",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cosmos_wallets_exporter_balance",
     "legendFormat": "{{chain}}, {{denom}}"
    }
   ]
  },
  {
   "title": "success?",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "cosmos_wallets_exporter_success",
     "legendFormat": "{{ chain }}"
    }
   ]
  },
  {
   "title": "query timings",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "cosmos_wallets_exporter_timings",
     "legendFormat": "{{ chain }}"
    }
   ]
  }
 ]
}