{
 "title": "validators overall",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This is a basic overview of all our validators.  \nWe aim to be 100% transparent, and this is a nice way to have an overview for out delegators and those who are curious.\n\nConsider staking with us!\n\n- [Sentinel](https://www.mintscan.io/sentinel/validators/sentvaloper1rw9wtyhsus7jvx55v3qv5nzun054ma6kz4237k)\n- [e-Money](https://www.mintscan.io/emoney/validators/emoneyvaloper1jk4n79c5gv36972ptnly3rvx5nvn3hl3hgly9g)\n- [Bitsong](https://www.mintscan.io/bitsong/validators/bitsongvaloper14rvn7anf22e00vj5x3al4w50ns78s7n42rc0ge)\n- [Decentr](https://explorer.decentr.net/validators/decentrvaloper1nuhk7uke8ux2h7zpg44u7gyksgkz0fcjpf2074?networkId=mainnet)\n- [Nomic](https://app.nomic.io/#/staking?validator=nomic1cugv7uxm0qw749jpjag5tw64k9wj0n3fe8vss5&modal=info)\n- [Jackal](https://ping.pub/jackal/staking/jklvaloper1ramqkapjkg0f58vypc43szaqp5juq0ly93t3hm)\n"
   }
  },
  { "title": "Overall stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "total validators monitored",
   "type": "stat",
   "description": "Nomic is not included here unfortunately as it's not cosmos-sdk compatible",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validators_exporter_info)",
     "legendFormat": "{{address}} @ {{ chain }}"
    }
   ]
  },
  {
   "title": "total secured",
   "type": "stat",
   "description": "Total amount of all the delegations on all chains we are validating",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum ((cosmos_validators_exporter_total_delegations) / on (chain) cosmos_validators_exporter_denom_coefficient * on (chain) cosmos_validators_exporter_price)",
     "legendFormat": "{{address}} @ {{ chain }}"
    }
   ]
  },
  {
   "title": "total delegators",
   "type": "stat",
   "description": "Total number of delegations on all our validators.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cosmos_validators_exporter_delegations_count)",
     "legendFormat": "{{address}} @ {{ chain }}"
    }
   ]
  },
  {
   "title": "total self-delegated",
   "type": "stat",
   "description": "Total amount of self-delegated tokens in USD on all the chains we're validating.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (cosmos_validators_exporter_self_delegated / on (chain) cosmos_validators_exporter_denom_coefficient * on (chain) cosmos_validators_exporter_price)",
     "legendFormat": "{{address}} @ {{ chain }}"
    }
   ]
  },
  {
   "title": "self-delegated %",
   "type": "stat",
   "description": "% of all our self-delegated tokens compared to all our delegations.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cosmos_validators_exporter_self_delegated / on (chain, address, moniker) cosmos_validators_exporter_total_delegations)",
     "legendFormat": "{{address}} @ {{ chain }}"
    }
   ]
  },
  {
   "title": "total rewards + collateral, $",
   "type": "stat",
   "description": "Total rewards (commission + self-delegated rewards) + collateral (self-delegated tokens) + wallet balance, in USD.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((cosmos_validators_exporter_self_delegation_rewards + cosmos_validators_exporter_unclaimed_commission + \ncosmos_validators_exporter_wallet_balance +\ncosmos_validators_exporter_self_delegated) / on (chain) cosmos_validators_exporter_denom_coefficient * on (chain) cosmos_validators_exporter_price)\n",
     "legendFormat": "{{address}} @ {{ chain }}"
    }
   ]
  },
  { "title": "Validators info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "delegators count",
   "type": "stat",
   "description": "Total amount of delegators by chain.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_delegations_count{moniker!=\"\"}",
     "legendFormat": "{{ chain }}"
    }
   ]
  },
  {
   "title": "delegations - $",
   "type": "timeseries",
   "description": "Total amount of secured tokens in $ on all our validators.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(cosmos_validators_exporter_total_delegations) / on (chain) cosmos_validators_exporter_denom_coefficient * on (chain) cosmos_validators_exporter_price",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "validator ranking",
   "type": "stat",
   "description": "Validator's position in ranking compared to other validators.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(cosmos_validators_exporter_rank{moniker!=\"\"})",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "voting power %",
   "type": "stat",
   "description": "Voting power of a validator compared to total bonded tokens.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_total_delegations / on (chain) cosmos_validators_exporter_tokens_bonded_total",
     "legendFormat": "{{ chain }}"
    }
   ]
  },
  {
   "title": "self-delegated info",
   "type": "table",
   "description": "Info about self-delegated tokens",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_self_delegated / on (chain, address, moniker) cosmos_validators_exporter_total_delegations",
     "legendFormat": "{{address}} @ {{ chain }}"
    },
    {
     "expr": "cosmos_validators_exporter_self_delegated / on (chain) cosmos_validators_exporter_denom_coefficient",
     "legendFormat": "__auto"
    },
    {
     "expr": "cosmos_validators_exporter_denom_coefficient",
     "legendFormat": "__auto"
    },
    {
     "expr": "cosmos_validators_exporter_self_delegated / on (chain) cosmos_validators_exporter_denom_coefficient * on (chain) group_left cosmos_validators_exporter_price",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "self-delegations amount, $",
   "type": "stat",
   "description": "Amount of tokens in $ we've self-delegated, per validator.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_self_delegated{moniker!=\"\"}  / on (chain) cosmos_validators_exporter_denom_coefficient * on (chain) cosmos_validators_exporter_price",
     "legendFormat": "{{ chain }}"
    }
   ]
  },
  {
   "title": "validators info",
   "type": "table",
   "description": "All info on our validators.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_commission",
     "legendFormat": "{{address}} @ {{ chain }}"
    },
    {
     "expr": "cosmos_validators_exporter_commission_max",
     "legendFormat": "{{address}} @ {{ chain }}"
    },
    {
     "expr": "cosmos_validators_exporter_commission_max_change",
     "legendFormat": "{{address}} @ {{ chain }}"
    },
    {
     "expr": "cosmos_validators_exporter_info",
     "legendFormat": "{{address}} @ {{ chain }}"
    }
   ]
  },
  { "title": "Chain info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "chain info",
   "type": "table",
   "description": "All info on our validators.",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_active_set_size",
     "legendFormat": "{{address}} @ {{ chain }}"
    },
    {
     "expr": "cosmos_validators_exporter_active_set_tokens / on (chain) cosmos_validators_exporter_denom_coefficient",
     "legendFormat": "{{address}} @ {{ chain }}"
    },
    {
     "expr": "cosmos_validators_exporter_total_delegations / on (chain) cosmos_validators_exporter_denom_coefficient",
     "legendFormat": "{{address}} @ {{ chain }}"
    },
    {
     "expr": "cosmos_validators_exporter_denom_coefficient",
     "legendFormat": "__auto"
    },
    {
     "expr": "cosmos_validators_exporter_validators_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "cosmos_validators_exporter_active_set_tokens / on (chain) cosmos_validators_exporter_denom_coefficient * on (chain) cosmos_validators_exporter_price",
     "legendFormat": "__auto"
    },
    {
     "expr": "cosmos_validators_exporter_total_delegations / on (chain) cosmos_validators_exporter_denom_coefficient * on (chain) cosmos_validators_exporter_price",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token price, $",
   "type": "stat",
   "description": "How much 1 token costs. Prices taken from Coingecko.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_price",
     "legendFormat": "{{ chain }}"
    }
   ]
  },
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "missed blocks",
   "type": "timeseries",
   "description": "Validators' missed blocks.",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (cosmos_validators_exporter_missed_blocks{moniker!=\"\"} / on (chain) cosmos_validators_exporter_missed_blocks_window)",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Missed blocks counter",
   "type": "stat",
   "description": "Amount of blocks the validator hasn't signed in the signing window (usually 10k, can be different from network to network). The lower, the better. If it's above a specific threshold (usually 95%, but also different from chain to chain) the validator goes to jail.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_missed_blocks{moniker!=\"\"}",
     "legendFormat": "{{ chain }}"
    }
   ]
  },
  { "title": "Validator revenue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "commission, $",
   "type": "timeseries",
   "description": "Validators' unclaimed commission.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_unclaimed_commission{denom!~\"ibc.*\",moniker!=\"\"}  / on (chain) cosmos_validators_exporter_denom_coefficient * on (chain) cosmos_validators_exporter_price",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "self-delegated rewards, $",
   "type": "timeseries",
   "description": "Rewards from the tokens staked to ourselves.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_self_delegation_rewards{moniker!=\"\",denom!~\"ibc.*\"} / on (chain) group_left cosmos_validators_exporter_denom_coefficient * on (chain) group_left cosmos_validators_exporter_price",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "wallet balance, $",
   "type": "timeseries",
   "description": "Validators' wallet balance.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_wallet_balance{moniker!=\"\",denom!~\"ibc.*\"} / on (chain) group_left cosmos_validators_exporter_denom_coefficient * on (chain) group_left cosmos_validators_exporter_price",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "total revenue, $",
   "type": "timeseries",
   "description": "Validators' rewards (self-delegated rewards + commission).",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(cosmos_validators_exporter_unclaimed_commission{moniker!=\"\",denom!~\"ibc.*\"}\n+ cosmos_validators_exporter_wallet_balance{moniker!=\"\"}\n+ cosmos_validators_exporter_self_delegation_rewards{moniker!=\"\",denom!~\"ibc.*\"}\n)  / on (chain) group_left cosmos_validators_exporter_denom_coefficient * on (chain) group_left cosmos_validators_exporter_price",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "total revenue + collateral current, $",
   "type": "stat",
   "description": "Validators' rewards (self-delegated rewards + commission) + validators' wallet balance + collateral (self-delegated tokens).",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(cosmos_validators_exporter_unclaimed_commission{moniker!=\"\"} + cosmos_validators_exporter_self_delegated{moniker!=\"\"} +\ncosmos_validators_exporter_wallet_balance{moniker!=\"\"} + cosmos_validators_exporter_self_delegation_rewards{moniker!=\"\"})  / on (chain) group_left cosmos_validators_exporter_denom_coefficient * on (chain) group_left cosmos_validators_exporter_price",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "rewards info",
   "type": "table",
   "description": "All info on our rewards, everything specified is in tokens.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_unclaimed_commission{denom!~\"ibc.*\",moniker!=\"\"}  / on (chain) cosmos_validators_exporter_denom_coefficient",
     "legendFormat": "{{address}} @ {{ chain }}"
    },
    {
     "expr": "cosmos_validators_exporter_denom_coefficient",
     "legendFormat": "{{address}} @ {{ chain }}"
    },
    {
     "expr": "cosmos_validators_exporter_self_delegation_rewards{moniker!=\"\",denom!~\"ibc.*\"} / on (chain) group_left cosmos_validators_exporter_denom_coefficient",
     "legendFormat": "{{address}} @ {{ chain }}"
    },
    {
     "expr": "cosmos_validators_exporter_wallet_balance{moniker!=\"\",denom!~\"ibc.*\"} / on (chain) group_left cosmos_validators_exporter_denom_coefficient",
     "legendFormat": "{{address}} @ {{ chain }}"
    }
   ]
  },
  { "title": "Debug info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "queries failed",
   "type": "timeseries",
   "description": "Total queries amount that have failed. If some RPC is failing a lot of requests, consider switching to another one or buy a better server if it's yours.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_queries_error",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "queries total",
   "type": "timeseries",
   "description": "Total queries done by cosmos-validators-exporter.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_queries_total",
     "legendFormat": "{{chain}}"
    }
   ]
  }
 ]
}