---
- name: Install Rust
  hosts: "{{ hosts | default('all') }}"

  vars:
    rustup_path: "{{ ansible_user_dir }}/rustup.sh"

  tasks:
    - name: Fetch rustup installer
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: "{{ rustup_path }}"
        mode: '0755'

    - name: Make rustup binary executable
      ansible.builtin.file:
        path: "{{ rustup_path }}"
        state: file
        mode: +x

    - name: Install Rust
      ansible.builtin.shell: "{{ rustup_path }} -y"
      args:
        executable: /bin/zsh
      register: result

    - name: Debug
      ansible.builtin.debug:
        var: result

    - name: Add ~/.zshrc aliases for rustup
      ansible.builtin.blockinfile:
        path: ~/.zshrc
        marker: "## {mark} added by ansible via playbook - rustup aliases"
        block: . $HOME/.cargo/env
