{
 "title": "blackbox_exporter",
 "description": "blackbox_exporter HTTP monitoring panel",
 "tags": [
  "http/https",
  "blackbox_exporter",
  "web",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "HTTP Monitoring Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(probe_success)" }
   ]
  },
  {
   "title": "Fail",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(probe_success == 0)" }
   ]
  },
  {
   "title": "Detailed Information",
   "type": "table",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 9 },
   "targets": [
    { "expr": "probe_http_status_code" },
    {
     "expr": "probe_ssl_earliest_cert_expiry{project=~\"$project\", app=~\"$app\"} - time()"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry * 1000"
    },
    {
     "expr": "sum(probe_http_duration_seconds) by (instance)"
    },
    { "expr": "probe_dns_lookup_time_seconds" }
   ]
  },
  {
   "title": "Instance status percentage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(probe_success == 1)", "legendFormat": "Success status instance" },
    {
     "expr": "count(probe_success{project=~\"$project\", app=~\"$app\"} == 0)",
     "legendFormat": "Failed status instance"
    }
   ]
  },
  {
   "title": "Instance whose certificate is about to expire",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "Expired in less than 30 days",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry - time() < (3600 * 24 * 30)"
    }
   ]
  },
  { "title": "Response code change record", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Response code change record",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "probe_http_status_code", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}