---
- name: Update Prometheus config
  hosts: "{{ hosts | default('monitoring')  }}"

  tasks:
    - name: Create Prometheus folders
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        group: prometheus
        owner: prometheus
      loop:
        - /etc/prometheus/rules.d
        - /etc/prometheus/targets.d

    - name: Copy Prometheus rules
      become: true
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/prometheus/rules.d
        mode: "0755"
      with_fileglob: "../../../templates/monitoring/prometheus/rules.d/**.yml"

    - name: Copy Prometheus targets
      become: true
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/prometheus/targets.d
        mode: "0755"
      with_fileglob: "../../../configs/prometheus/{{ inventory_hostname }}/targets.d/**.json"

    - name: Copy Prometheus config
      become: true
      ansible.builtin.copy:
        src: ../../../configs/prometheus/{{ inventory_hostname }}/prometheus.yml
        dest: /etc/prometheus/prometheus.yml
        mode: "0755"

    - name: Verify Prometheus config
      become: true
      ansible.builtin.command: promtool check config /etc/prometheus/prometheus.yml
      changed_when: false
      register: prometheus_config

    - name: Print Prometheus config validation result
      ansible.builtin.debug:
        msg:
          - "Stdout:"
          - "{{ (prometheus_config.stdout).split('\n') }}"
          - "Stderr:"
          - "{{ (prometheus_config.stderr).split('\n') }}"

    - name: Reload Prometheus config
      ansible.builtin.uri:
        url: http://localhost:9090/-/reload
        user: "{{ prometheus_username }}"
        password: "{{ prometheus_password }}"
        method: POST
        body: ""
        force_basic_auth: true
