groups:
  - name: CosmosValidatorsExporterAlerts
    rules:
      - alert: CosmosValidatorsExporterNodeError
        expr: cosmos_validators_exporter_queries_error > 0
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: cosmos-validators-exporter has some errors
          description: "cosmos-validators-exporter has some errors from chain  from chain (instance {{ $labels.instance }}, chain {{ $labels.chain }}): {{ $value }}"

      - alert: CosmosValidatorsExporterValidatorAtLastPlace
        expr: cosmos_validators_exporter_validators_count - cosmos_validators_exporter_rank <= 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Cosmos validator is at the last place (instance {{ $labels.instance }})
          description: "Cosmos validator is at the last place"
