---
- name: Install blackbox-exporter
  hosts: "{{ hosts | default('monitoring') }}"
  roles:
    - prometheus.prometheus.blackbox_exporter
  vars:
    blackbox_exporter_configuration_modules:
      http_2xx:
        http:
          method: GET
          valid_status_codes: []
          headers:
            User-Agent: "blackbox_exporter"
        prober: http
        timeout: 5s
