{
 "title": "proxmox",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "cpu usage ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio * on (id, host) group_right pve_guest_info",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(pve_memory_usage_bytes / pve_memory_size_bytes) * on(id, host) group_left(name) pve_guest_info",
     "legendFormat": "{{ name }} @ {{ host }}"
    }
   ]
  },
  {
   "title": "disk usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(pve_disk_usage_bytes / pve_disk_size_bytes) * on(id, host) group_left(name) pve_guest_info",
     "legendFormat": "{{ name }} @ {{ host }}"
    }
   ]
  },
  {
   "title": "network in",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(pve_network_receive_bytes[1m]) * on (id, host) group_right pve_guest_info",
     "legendFormat": "{{ name }}@{{ node }}"
    }
   ]
  },
  {
   "title": "network out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(pve_network_transmit_bytes[1m]) * on (id, host) group_right pve_guest_info",
     "legendFormat": "{{ name }}@{{ host }}"
    }
   ]
  },
  {
   "title": "disk reads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(pve_disk_read_bytes[1m]) * on (id, host) group_right pve_guest_info",
     "legendFormat": "{{ name}}@{{ host }}"
    }
   ]
  },
  {
   "title": "disk writes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(pve_disk_write_bytes[1m]) * on (id, host) group_right pve_guest_info",
     "legendFormat": "{{ name }}@{{ node }}"
    }
   ]
  },
  {
   "title": "VM stats",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(pve_up * on (id, host) group_right pve_guest_info) by (node, name, type)",
     "legendFormat": "{{ name}}@{{ node }}"
    },
    {
     "expr": "sum(pve_memory_size_bytes * on (id, host) group_right pve_guest_info) by (name)",
     "legendFormat": "{{ name}}@{{ node }}"
    },
    {
     "expr": "sum(pve_cpu_usage_limit * on (id, host) group_right pve_guest_info) by (name)",
     "legendFormat": "{{ name}}@{{ node }}"
    },
    {
     "expr": "sum(pve_disk_size_bytes * on (id, host) group_right pve_guest_info) by (name)",
     "legendFormat": "{{ name}}@{{ node }}"
    },
    {
     "expr": "sum((pve_memory_usage_bytes / pve_memory_size_bytes) * on(id, host) group_left(name) pve_guest_info) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(pve_cpu_usage_ratio * on (id, host) group_right pve_guest_info) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum((pve_disk_usage_bytes / pve_disk_size_bytes) * on(id, host) group_left(name) pve_guest_info) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Hosts stats",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(pve_up * on (id, host) group_right pve_node_info) by (name)",
     "legendFormat": "{{ name}}@{{ node }}"
    },
    {
     "expr": "sum(pve_memory_size_bytes * on (id, host) group_right pve_node_info) by (name)",
     "legendFormat": "{{ name}}@{{ node }}"
    },
    {
     "expr": "sum(pve_cpu_usage_limit * on (id, host) group_right pve_node_info) by (name)",
     "legendFormat": "{{ name}}@{{ node }}"
    },
    {
     "expr": "sum(pve_disk_size_bytes * on (id, host) group_right pve_node_info) by (name)",
     "legendFormat": "{{ name}}@{{ node }}"
    },
    {
     "expr": "sum((pve_memory_usage_bytes / pve_memory_size_bytes) * on(id, host) group_left(name) pve_node_info) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(pve_cpu_usage_ratio * on (id, host) group_right pve_node_info) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum((pve_disk_usage_bytes / pve_disk_size_bytes) * on(id, host) group_left(name) pve_node_info) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hosts resources utilization",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(pve_up * on (id, host) group_right pve_node_info) by (name, id)",
     "legendFormat": "{{ name}}@{{ node }}"
    },
    {
     "expr": "sum(pve_memory_size_bytes * on (id, host) group_right pve_node_info) by (name)",
     "legendFormat": "{{ name}}@{{ node }}"
    },
    {
     "expr": "sum(pve_cpu_usage_limit * on (id, host) group_right pve_node_info) by (name)",
     "legendFormat": "{{ name}}@{{ node }}"
    },
    {
     "expr": "sum(\n    label_replace(\n        sum(\n            pve_cpu_usage_limit\n            * on (id, host) group_right pve_guest_info\n        ) by (node),\n        \"name\",\n        \"$1\",\n        \"node\",\n        \"(.+)\"\n    )\n) by (name)\n/\nsum(\n    pve_cpu_usage_limit\n    * on (id, host) group_right pve_node_info\n) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    label_replace(\n        sum(\n            pve_memory_size_bytes\n            * on (id, host) group_right pve_guest_info\n        ) by (node),\n        \"name\",\n        \"$1\",\n        \"node\",\n        \"(.+)\"\n    )\n) by (name)\n/\nsum(\n    pve_memory_size_bytes\n    * on (id, host) group_right pve_node_info\n) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    label_replace(\n        sum(\n            pve_cpu_usage_limit\n            * on (id, host) group_right pve_guest_info\n        ) by (node),\n        \"name\",\n        \"$1\",\n        \"node\",\n        \"(.+)\"\n    )\n) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    label_replace(\n        sum(\n            pve_memory_size_bytes\n            * on (id, host) group_right pve_guest_info\n        ) by (node),\n        \"name\",\n        \"$1\",\n        \"node\",\n        \"(.+)\"\n    )\n) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    label_replace(\n        sum(\n            pve_disk_size_bytes\n            * on (id, host) group_right pve_storage_info\n        ) by (node),\n        \"name\",\n        \"$1\",\n        \"node\",\n        \"(.+)\"\n    )\n) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    label_replace(\n        sum(\n            pve_disk_usage_bytes\n            * on (id, host) group_right pve_storage_info\n        ) by (node),\n        \"name\",\n        \"$1\",\n        \"node\",\n        \"(.+)\"\n    )\n) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    label_replace(\n        sum(\n            pve_disk_usage_bytes\n            * on (id, host) group_right pve_storage_info\n        ) by (node)\n        / \n        sum(\n            pve_disk_size_bytes\n            * on (id, host) group_right pve_storage_info\n        ) by (node),\n        \"name\",\n        \"$1\",\n        \"node\",\n        \"(.+)\"\n    )\n) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "total network in",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(pve_network_receive_bytes[1m]) * on (id, host) group_right pve_guest_info) by (node, host)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "total network out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(pve_network_transmit_bytes[1m]) * on (id, host) group_right pve_guest_info) by (node, host)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Storage info",
   "type": "table",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum(pve_storage_shared * on (id, host) group_right pve_storage_info) by (id, node, storage)",
     "legendFormat": "{{ name}}@{{ node }}"
    },
    {
     "expr": "sum(pve_disk_size_bytes * on (id, host) group_right pve_storage_info) by (id)",
     "legendFormat": "{{ name}}@{{ node }}"
    },
    {
     "expr": "sum(pve_disk_usage_bytes * on (id, host) group_right pve_storage_info) by (id)",
     "legendFormat": "{{ name}}@{{ node }}"
    },
    {
     "expr": "sum(pve_disk_usage_bytes / pve_disk_size_bytes * on (id, host) group_right pve_storage_info) by (id)",
     "legendFormat": "{{ name}}@{{ node }}"
    }
   ]
  },
  {
   "title": "disk size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(pve_disk_usage_bytes / pve_disk_size_bytes * on (id, host) group_right pve_storage_info) by (storage, node)",
     "legendFormat": "{{storage}}@{{node}}"
    }
   ]
  }
 ]
}