---
- name: Update rly config
  hosts: "{{ hosts | default('monitoring')  }}"

  tasks:
    - name: Copy rly config
      ansible.builtin.copy:
        src: "../../configs/rly/{{ inventory_hostname }}.yml"
        dest: "{{ ansible_user_dir }}/.relayer/config/config.yaml"
        mode: "0755"

    - name: Restart rly
      become: true
      ansible.builtin.systemd:
        state: restarted
        name: rly
        enabled: true
        daemon_reload: true
