{
 "title": "node-exporter disk graphs",
 "description": "Prometheus + node-exporter dashboard for viewing disk performance, utilization and saturation.",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "Host",
    "query": {
     "query": "label_values(node_time_seconds, host)"
    }
   },
   {
    "name": "CPU",
    "query": {
     "query": "label_values(node_cpu_seconds_total{host=~\"$Host\"}, cpu)"
    }
   },
   {
    "name": "Disk",
    "query": {
     "query": "label_values(node_disk_write_time_seconds_total{host=~\"$Host\"}, device)"
    }
   },
   { "name": "RateInterval", "query": "20s,1m,5m" }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_bytes{host=~\"$Host\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Memory active {{ host }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$Node\"}",
     "legendFormat": "Memory buffers {{ host }}"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$Node\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Memory cached {{ instance }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$Node\"}",
     "legendFormat": "Total memory {{ host }}"
    }
   ]
  },
  {
   "title": "Memory write cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Dirty_bytes{host=~\"$Host\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Dirty bytes {{ host }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "node_memory_Writeback_bytes{host=~\"$Host\"}",
     "legendFormat": "Writeback bytes {{ host }}"
    }
   ]
  },
  {
   "title": "OOM killed procs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_vmstat_oom_kill{host=~\"$Host\"}[$RateInterval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ host }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "IO Wait per core",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{cpu=~\"$CPU\", host=~\"$Host\", mode=\"iowait\"}[$RateInterval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ host }} CPU {{ cpu }}/{{ mode }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "min(rate(node_cpu_seconds_total{cpu=~\"$CPU\", host=~\"$Host\", mode=\"iowait\"}[$RateInterval]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{cpu=~\"$CPU\", host=~\"$Host\", mode=\"iowait\"}[$RateInterval]))",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(rate(node_cpu_seconds_total{cpu=~\"$CPU\", host=~\"$Host\", mode=\"iowait\"}[$RateInterval]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Disk active time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{host=~\"$Host\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ host }} {{ device }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{host=~\"$Host\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
     "legendFormat": "Weighted IO time {{ device }} {{ host }}"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{host=~\"$Host\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
     "legendFormat": "Write time {{ device }} {{ host }}"
    },
    {
     "expr": "rate(node_disk_read_time_seconds_total{host=~\"$Host\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
     "legendFormat": "Read time {{ device }} {{ host }}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{host=~\"$Host\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ host }} {{ device }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Write bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": " rate(node_disk_written_bytes_total{host=~\"$Host\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval]) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ host }} {{ device }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Write size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{host=~\"$Host\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval]) / rate(node_disk_writes_completed_total{host=~\"$Host\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ host }} {{ device }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Write latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_write_time_seconds_total{host=~\"$Host\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval]) /  rate(node_disk_writes_completed_total{host=~\"$Host\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ host }} {{ device }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Read bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": " rate(node_disk_read_bytes_total{host=~\"$Host\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval]) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ host }} {{ device }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Read size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{host=~\"$Host\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval]) / rate(node_disk_reads_completed_total{host=~\"$Host\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ host }} {{ device }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Read latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{host=~\"$Host\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval]) /  rate(node_disk_reads_completed_total{host=~\"$Host\", device!=\"sr0\", device=~\"$Disk\"}[$RateInterval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ host }} {{ device }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}