{
 "title": "machine metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "loadavg 1",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_load1 / count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"}) * 100",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "cpu load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance, host) (avg by (mode, instance, host) (rate(node_cpu_seconds_total{mode!=\"idle\"}[2m])))",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "loadavg 15",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_load15 / count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"}) * 100",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "mem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "disk space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint!~\"/(run|tmp|boot).*\", device!=\"rootfs\"} / node_filesystem_size_bytes) * 100",
     "legendFormat": "{{ mountpoint}} @ {{ host }}"
    }
   ]
  },
  {
   "title": "temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(node_hwmon_temp_celsius) by (chip, host)",
     "legendFormat": "{{chip}}@{{host}}"
    }
   ]
  },
  {
   "title": "disk write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum by (instance, host) (rate(node_disk_written_bytes_total[10m])) / 1024 / 1024",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "disk read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum by (instance, host) (rate(node_disk_read_bytes_total[10m])) / 1024 / 1024",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "failed systemd jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_systemd_units{state=\"failed\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "net incoming",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total[5m])) by (host)",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "net outgoing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total[5m])) by (host)",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "hosts stats",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "{{ host }}" },
    {
     "expr": "count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"})",
     "legendFormat": "{{ host }}"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"}",
     "legendFormat": "{{ host }}"
    },
    { "expr": "node_uname_info", "legendFormat": "{{host}}" }
   ]
  }
 ]
}