---
- name: Install Golang
  hosts: "{{ hosts }}"

  tasks:
    - name: Install required packages
      become: true
      apt:
        name:
          - software-properties-common
          - dirmngr
        state: latest
        update_cache: true

    - name: Add Golang repository
      when: use_golang_backports is defined and use_golang_backports == true
      become: true
      ansible.builtin.apt_repository:
        repo: 'ppa:longsleep/golang-backports'

    - name: Install Golang package
      become: true
      apt:
        name: golang-go
        state: latest
        update_cache: true

    - name: Add shell aliases for Golang folders
      blockinfile:
        path: "{{ shell_config_path | default('~/.zshrc', true) }}"
        marker: "## {mark} added by ansible via playbook - Golang aliases"
        block: |
          export GOROOT=/usr/lib/go
          export GOPATH=${HOME}/go
          export GOBIN=$GOPATH/bin
          export PATH=${PATH}:${GOROOT}/bin:${GOBIN}

    - name: Check version
      ansible.builtin.shell: "go version"
      register: result

    - name: Display version
      debug:
        msg: "{{ result.stderr }}{{ result.stdout }}"
