---
- name: Set up statesync
  hosts: "{{ hosts | default('fullnodes') }}"

  environment:
    GOROOT: /usr/lib/go
    GOPATH: "{{ ansible_env.HOME }}/go"
    GOBIN: "{{ ansible_env.HOME }}/go/bin"
    PATH: "{{ ansible_env.PATH }}:/usr/lib/go/bin:{{ ansible_env.HOME }}/go/bin"

  vars:
    config_path: "{{ fullnode_folder }}/config/config.toml"
    blocks_behind: 1000

  tasks:
    - name: Install required packages
      become: true
      ansible.builtin.apt:
        name:
          - jq
          - curl
        state: latest
        update_cache: true

    - name: Enable statesync
      community.general.ini_file:
        path: "{{ config_path }}"
        section: statesync
        option: enable
        value: "true"
        mode: '0755'

    - name: Fetch latest block
      ansible.builtin.shell: curl -s {{ statesync_node }}/block | jq -r .result.block.header.height
      args:
        executable: /bin/bash
      register: latest_block

    - name: Fetch statesync block
      ansible.builtin.shell: curl -s '{{ statesync_node }}/block?height={{ latest_block.stdout | int - blocks_behind }}' | jq -r .result.block_id.hash
      args:
        executable: /bin/bash
      register: statesync_block_hash

    - name: Set up statesync nodes in config
      community.general.ini_file:
        path: "{{ config_path }}"
        section: statesync
        option: rpc_servers
        value: '"{{ statesync_node }},{{ statesync_node }}"'
        mode: '0755'

    - name: Set up statesync trust height in config
      community.general.ini_file:
        path: "{{ config_path }}"
        section: statesync
        option: trust_height
        value: "{{ latest_block.stdout | int - blocks_behind }}"
        mode: '0755'

    - name: Set up statesync trust hash in config
      community.general.ini_file:
        path: "{{ config_path }}"
        section: statesync
        option: trust_hash
        value: '"{{ statesync_block_hash.stdout }}"'
        mode: '0755'
