---
- name: Install cosmos-node-exporter
  hosts: "{{ hosts | default('fullnodes') }}"

  environment:
    GOROOT: /usr/lib/go
    GOPATH: "{{ ansible_env.HOME }}/go"
    GOBIN: "{{ ansible_env.HOME }}/go/bin"
    PATH: "{{ ansible_env.PATH }}:/usr/lib/go/bin:{{ ansible_env.HOME }}/go/bin"

  tasks:
    - name: Install required packages
      become: true
      ansible.builtin.apt:
        name:
          - git
          - build-essential
        state: latest
        update_cache: true

    - name: Clone the repo
      ansible.builtin.git:
        repo: https://github.com/QuokkaStake/cosmos-node-exporter
        dest: "{{ ansible_user_dir }}/cosmos-node-exporter"
        version: main
        update: true

    - name: Install binary
      community.general.make:
        chdir: "{{ ansible_user_dir }}/cosmos-node-exporter"
        target: install

    - name: Create config directory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/config"
        state: directory
        mode: '0755'

    - name: Generate config
      ansible.builtin.template:
        src: ../../templates/fullnode/cosmos-node-exporter.toml.j2
        dest: "{{ ansible_user_dir }}/config/cosmos-node-exporter.toml"
        mode: '0755'

    - name: Generate systemd file
      become: true
      ansible.builtin.template:
        src: ../../templates/fullnode/cosmos-node-exporter.service.j2
        dest: /etc/systemd/system/cosmos-node-exporter.service
        mode: '0644'

    - name: Verify config # noqa: command-instead-of-module risky-shell-pipe
      become: true
      ansible.builtin.shell: >
          {{ ansible_user_dir }}/go/bin/cosmos-node-exporter validate-config
          --config {{ ansible_user_dir }}/config/cosmos-node-exporter.toml | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2};?)?)?[mGK]//g"
      changed_when: false
      register: config_output

    - name: Print config validation result
      ansible.builtin.debug:
        msg:
          - "Stdout:"
          - "{{ (config_output.stdout).split('\n') }}"
          - "Stderr:"
          - "{{ (config_output.stderr).split('\n') }}"

    - name: Start the service
      become: true
      ansible.builtin.systemd:
        state: restarted
        name: cosmos-node-exporter
        enabled: true
        daemon_reload: true
