---
- name: Install cosmos-node-exporter
  hosts: "{{ hosts | default('fullnodes') }}"

  environment:
    GOROOT: /usr/lib/go
    GOPATH: "{{ ansible_env.HOME }}/go"
    GOBIN: "{{ ansible_env.HOME }}/go/bin"
    PATH: "{{ ansible_env.PATH }}:/usr/lib/go/bin:{{ ansible_env.HOME }}/go/bin"

  tasks:
    - name: Clone the repo
      ansible.builtin.git:
        repo: "https://github.com/QuokkaStake/cosmos-node-exporter"
        dest: "{{ ansible_user_dir }}/cosmos-node-exporter"
        version: main
        update: true

    - name: Get services list
      service_facts:
      register: services

    - name: Stop service
      become: true
      systemd:
        name: cosmos-node-exporter
        state: stopped
      when: "'cosmos-node-exporter.service' in services.ansible_facts.services"

    - name: Install binary
      make:
        chdir: "{{ ansible_user_dir }}/cosmos-node-exporter"
        target: install

    - name: Create config directory
      file:
        path: "{{ ansible_user_dir }}/config"
        state: directory

    - name: Generate config
      ansible.builtin.template:
        src: ../../templates/fullnode/cosmos-node-exporter.toml.j2
        dest: "{{ ansible_user_dir }}/config/cosmos-node-exporter.toml"

    - name: Generate systemd file
      become: true
      ansible.builtin.template:
        src: ../../templates/fullnode/cosmos-node-exporter.service.j2
        dest: /etc/systemd/system/cosmos-node-exporter.service

    - name: Start the service
      become: true
      ansible.builtin.systemd:
        state: started
        name: cosmos-node-exporter
        enabled: true
        daemon_reload: true
