---
- name: Install tendermint-exporter
  hosts: "{{ hosts }}"

  environment:
    GOROOT: /usr/lib/go
    GOPATH: "{{ ansible_env.HOME }}/go"
    GOBIN: "{{ ansible_env.HOME }}/go/bin"
    PATH: "{{ ansible_env.PATH }}:/usr/lib/go/bin:{{ ansible_env.HOME }}/go/bin"

  tasks:
    - name: Clone the repo
      ansible.builtin.git:
        repo: "https://github.com/solarlabsteam/tendermint-exporter"
        dest: "{{ ansible_user_dir }}/tendermint-exporter"
        version: master
        update: true

    - name: Get services list
      service_facts:
      register: services

    - name: Stop service
      become: true
      systemd:
        name: tendermint-exporter
        state: stopped
      when: "'tendermint-exporter.service' in services.ansible_facts.services"

    - name: Install binary
      ansible.builtin.shell: go build -buildvcs=false
      args:
        executable: /bin/bash
        chdir: "{{ ansible_user_dir }}/tendermint-exporter"

    - name: Copy binary to the correct folder
      become: true
      ansible.builtin.copy:
        src: "{{ ansible_user_dir }}/tendermint-exporter/main"
        dest: /usr/bin/tendermint-exporter
        remote_src: true
        mode: a+x

    - name: Create config directory
      file:
        path: "{{ ansible_user_dir }}/config"
        state: directory

    - name: Generate config
      ansible.builtin.template:
        src: ../../templates/fullnode/tendermint-exporter.toml.j2
        dest: "{{ ansible_user_dir }}/config/tendermint-exporter.toml"

    - name: Generate systemd file
      become: true
      ansible.builtin.template:
        src: ../../templates/fullnode/tendermint-exporter.service.j2
        dest: /etc/systemd/system/tendermint-exporter.service

    - name: Start the service
      become: true
      ansible.builtin.systemd:
        state: started
        name: tendermint-exporter
        enabled: true
