---
- name: Prepare Cosmovisor upgrade
  hosts: "{{ hosts }}"

  environment:
    GOROOT: /usr/lib/go
    GOPATH: "{{ ansible_env.HOME }}/go"
    GOBIN: "{{ ansible_env.HOME }}/go/bin"
    PATH: "{{ ansible_env.PATH }}:/usr/lib/go/bin:{{ ansible_env.HOME }}/go/bin"

  tasks:
    - name: Checkout to the upgrade tag
      ansible.builtin.git:
        repo: "{{ github_repo_remote }}"
        dest: "{{ github_repo_local }}"
        version: "{{ upgrade_version }}"
        update: true

    # - name: Build the binary
    #   make:
    #     chdir: "{{ github_repo_local }}"
    #     target: install

    - name: Create upgrade folders layout
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ fullnode_folder }}"
        - "{{ fullnode_folder }}/cosmovisor"
        - "{{ fullnode_folder }}/cosmovisor/upgrades"
        - "{{ fullnode_folder }}/cosmovisor/upgrades/{{ upgrade_name }}"
        - "{{ fullnode_folder }}/cosmovisor/upgrades/{{ upgrade_name }}/bin"

    - name: Copy binary to Cosmovisor folder
      ansible.builtin.copy:
        src: "{{ ansible_env.HOME }}/go/bin/{{ binary_name }}"
        dest: "{{ fullnode_folder }}/cosmovisor/upgrades/{{ upgrade_name }}/bin"
        mode: +x
        remote_src: true

    - name: Get latest version
      ansible.builtin.shell: "{{ fullnode_folder }}/cosmovisor/upgrades/{{ upgrade_name }}/bin/{{ binary_name }} version"
      register: version
      args:
        executable: /bin/bash

    - name: Print version
      debug:
        msg: "{{ version.stderr }}"
