{
 "title": "balances",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "tokens",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cosmos_wallets_exporter_balance",
     "legendFormat": "{{name}}, {{denom}}"
    }
   ]
  },
  {
   "title": "tokens delta",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "delta(cosmos_wallets_exporter_balance[5m]) != 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "balances",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "cosmos_wallets_exporter_balance * on (chain, denom) group_left cosmos_wallets_exporter_price",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "success?",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "cosmos_wallets_exporter_success",
     "legendFormat": "{{ chain }}"
    }
   ]
  },
  {
   "title": "query timings",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg(cosmos_wallets_exporter_timings) by (chain)",
     "legendFormat": "{{ chain }}"
    }
   ]
  }
 ]
}