{
 "title": "validators overall",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This is a basic overview of all our validators.  \nWe aim to be 100% transparent, and this is a nice way to have an overview for out delegators and those who are curious.\n\nConsider staking with us!\n\n- [Sentinel](https://www.mintscan.io/sentinel/validators/sentvaloper1rw9wtyhsus7jvx55v3qv5nzun054ma6kz4237k)\n- [Gitopia](https://ping.pub/gitopia/staking/gitopiavaloper1w52vzp25uj9zvd0rtt6s6stud3ff8n3pzklusg)\n- [Bitsong](https://www.mintscan.io/bitsong/validators/bitsongvaloper14rvn7anf22e00vj5x3al4w50ns78s7n42rc0ge)\n- [Decentr](https://explorer.decentr.net/validators/decentrvaloper1nuhk7uke8ux2h7zpg44u7gyksgkz0fcjpf2074?networkId=mainnet)\n- [Nomic](https://app.nomic.io/#/staking?validator=nomic1cugv7uxm0qw749jpjag5tw64k9wj0n3fe8vss5&modal=info)\n- [Jackal](https://ping.pub/jackal/staking/jklvaloper1ramqkapjkg0f58vypc43szaqp5juq0ly93t3hm)\n- [Cosmos Hub](https://www.mintscan.io/cosmos/validators/cosmosvaloper1xqz9pemz5e5zycaa89kys5aw6m8rhgsvw4328e)"
   }
  },
  { "title": "Overall stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "total validators monitored",
   "type": "stat",
   "description": "Nomic is not included here unfortunately as it's not cosmos-sdk compatible",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validators_exporter_active)",
     "legendFormat": "{{address}} @ {{ chain }}"
    }
   ]
  },
  {
   "title": "total secured",
   "type": "stat",
   "description": "Total amount of all the delegations on all chains we are validating",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cosmos_validators_exporter_total_delegations * on (chain, denom) cosmos_validators_exporter_price)",
     "legendFormat": "{{address}} @ {{ chain }}"
    }
   ]
  },
  {
   "title": "total secured diff",
   "type": "stat",
   "description": "The difference of total secured $ between last and first graph points.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(cosmos_validators_exporter_total_delegations * on (chain, denom) cosmos_validators_exporter_price)",
     "legendFormat": "{{address}} @ {{ chain }}"
    }
   ]
  },
  {
   "title": "total delegators",
   "type": "stat",
   "description": "Total number of delegations on all our validators.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cosmos_validators_exporter_delegations_count)",
     "legendFormat": "{{address}} @ {{ chain }}"
    }
   ]
  },
  {
   "title": "total self-delegated",
   "type": "stat",
   "description": "Total amount of self-delegated tokens in USD on all the chains we're validating.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (cosmos_validators_exporter_self_delegated * on (chain, denom) cosmos_validators_exporter_price)",
     "legendFormat": "{{address}} @ {{ chain }}"
    }
   ]
  },
  {
   "title": "total rewards, $",
   "type": "stat",
   "description": "Total rewards (commission + self-delegated rewards) + wallet balance, in USD.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((cosmos_validators_exporter_unclaimed_commission\n+ cosmos_validators_exporter_wallet_balance\n+ cosmos_validators_exporter_self_delegation_rewards\n) * on (chain, denom) group_left cosmos_validators_exporter_price)",
     "legendFormat": "{{address}} @ {{ chain }}"
    }
   ]
  },
  {
   "title": "total rewards + collateral, $",
   "type": "stat",
   "description": "Total rewards (commission + self-delegated rewards) + collateral (self-delegated tokens) + wallet balance, in USD.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((cosmos_validators_exporter_self_delegation_rewards + cosmos_validators_exporter_unclaimed_commission + \ncosmos_validators_exporter_wallet_balance +\ncosmos_validators_exporter_self_delegated) * on (chain, denom) cosmos_validators_exporter_price)\n",
     "legendFormat": "{{address}} @ {{ chain }}"
    }
   ]
  },
  { "title": "Validators info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "delegators count",
   "type": "stat",
   "description": "Total amount of delegators by chain.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_delegations_count",
     "legendFormat": "{{ chain }}"
    }
   ]
  },
  {
   "title": "delegations - $",
   "type": "timeseries",
   "description": "Total amount of secured tokens in $ on all our validators.",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_total_delegations * on (chain, denom) cosmos_validators_exporter_price",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "validator ranking",
   "type": "stat",
   "description": "Validator's position in ranking compared to other validators.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(avg(cosmos_validators_exporter_rank) by (chain, address))",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "delegations - $",
   "type": "stat",
   "description": "Total amount of secured tokens in $ on all our validators.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_total_delegations * on (chain, denom) cosmos_validators_exporter_price",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "voting power %",
   "type": "stat",
   "description": "Voting power of a validator compared to total bonded tokens.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_total_delegations / on (chain) cosmos_validators_exporter_tokens_bonded_total",
     "legendFormat": "{{ chain }}"
    }
   ]
  },
  {
   "title": "validators info",
   "type": "table",
   "description": "All info on our validators.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(cosmos_validators_exporter_commission) by (address, chain)",
     "legendFormat": "{{address}} @ {{ chain }}"
    },
    {
     "expr": "sum(cosmos_validators_exporter_commission_max) by (address, chain)",
     "legendFormat": "{{address}} @ {{ chain }}"
    },
    {
     "expr": "sum(cosmos_validators_exporter_commission_max_change) by (address, chain)",
     "legendFormat": "{{address}} @ {{ chain }}"
    },
    {
     "expr": "sum(cosmos_validators_exporter_info) by (address, chain, details, identity, moniker, security_contact, website)",
     "legendFormat": "{{address}} @ {{ chain }}"
    },
    {
     "expr": "sum(cosmos_validators_exporter_active) by (address, chain)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Self-delegation info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "self-delegated info",
   "type": "table",
   "description": "Info about self-delegated tokens",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(cosmos_validators_exporter_self_delegated / on (chain, address, moniker) cosmos_validators_exporter_total_delegations) by (chain)",
     "legendFormat": "{{address}} @ {{ chain }}"
    },
    {
     "expr": "sum(cosmos_validators_exporter_self_delegated) by (chain, denom)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(cosmos_validators_exporter_self_delegated * on (chain, denom) group_left cosmos_validators_exporter_price) by (chain)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "self-delegations amount, $",
   "type": "stat",
   "description": "Amount of tokens in $ we've self-delegated, per validator.",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_self_delegated * on (chain, denom) cosmos_validators_exporter_price",
     "legendFormat": "{{ chain }}"
    }
   ]
  },
  { "title": "Chain info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "active set info",
   "type": "table",
   "description": "Info on sovereign/provider chains and their active set.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cosmos_validators_exporter_active_set_size * (1 - cosmos_validators_exporter_is_consumer)) by (chain) > 0",
     "legendFormat": "{{address}} @ {{ chain }}"
    },
    {
     "expr": "sum(cosmos_validators_exporter_active_set_tokens) by (chain)",
     "legendFormat": "{{address}} @ {{ chain }}"
    },
    {
     "expr": "sum(cosmos_validators_exporter_total_delegations) by (chain)",
     "legendFormat": "{{address}} @ {{ chain }}"
    },
    {
     "expr": "sum(cosmos_validators_exporter_validators_count * (1 - cosmos_validators_exporter_is_consumer)) by (chain) > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    cosmos_validators_exporter_active_set_tokens\n    * on (chain, denom) cosmos_validators_exporter_price\n) by (chain)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    cosmos_validators_exporter_total_delegations\n    * on (chain, denom) cosmos_validators_exporter_price\n) by (chain)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "chain info",
   "type": "table",
   "description": "All info about the chains we're validating.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_chain_info",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(cosmos_validators_exporter_inflation) by (chain)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(cosmos_validators_exporter_supply * on (chain, denom) cosmos_validators_exporter_price) by (chain)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Consumer chains info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "consumer chain info",
   "type": "table",
   "description": "All info on consumer chains.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cosmos_validators_exporter_active_set_size) by (chain)",
     "legendFormat": "{{address}} @ {{ chain }}"
    },
    {
     "expr": "sum(cosmos_validators_exporter_validators_count) by (chain)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(cosmos_validators_exporter_soft_opt_out_threshold) by (chain)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(cosmos_validators_exporter_threshold_percent) by (chain)",
     "legendFormat": "{{address}} @ {{ chain }}"
    },
    {
     "expr": "sum(cosmos_validators_exporter_minimal_stake) by (chain)",
     "legendFormat": "{{address}} @ {{ chain }}"
    }
   ]
  },
  {
   "title": "consumer validators info",
   "type": "table",
   "description": "All info on consumer validators.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cosmos_validators_exporter_needs_to_sign) by (chain, address, provider)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(cosmos_validators_exporter_commission * on (chain)cosmos_validators_exporter_is_consumer) by (chain, address, provider) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Price info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Token price, $",
   "type": "stat",
   "description": "How much 1 token costs. Prices taken from Coingecko.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_price",
     "legendFormat": "{{ chain }} {{denom }}"
    }
   ]
  },
  {
   "title": "Price diff, $",
   "type": "stat",
   "description": "How much 1 token costs. Prices taken from Coingecko.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "delta(cosmos_validators_exporter_price[$__range])",
     "legendFormat": "{{ chain }} {{ denom }}"
    }
   ]
  },
  {
   "title": "Price long-term, $",
   "type": "timeseries",
   "description": "How much 1 token costs. Prices taken from Coingecko.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_price",
     "legendFormat": "{{ chain }} {{ denom }}"
    }
   ]
  },
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "missed blocks",
   "type": "timeseries",
   "description": "Validators' missed blocks.",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (avg(cosmos_validators_exporter_missed_blocks) by (chain, address) / on (chain) cosmos_validators_exporter_missed_blocks_window)",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Missed blocks counter",
   "type": "stat",
   "description": "Amount of blocks the validator hasn't signed in the signing window (usually 10k, can be different from network to network). The lower, the better. If it's above a specific threshold (usually 95%, but also different from chain to chain) the validator goes to jail.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cosmos_validators_exporter_missed_blocks) by (chain, address)",
     "legendFormat": "{{ chain }}"
    }
   ]
  },
  { "title": "Validator revenue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 } },
  {
   "title": "commission, $",
   "type": "timeseries",
   "description": "Validators' unclaimed commission.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(cosmos_validators_exporter_unclaimed_commission{} * on (chain, denom) cosmos_validators_exporter_price) by (chain)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "self-delegated rewards, $",
   "type": "timeseries",
   "description": "Rewards from the tokens staked to ourselves.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(cosmos_validators_exporter_self_delegation_rewards * on (chain, denom) group_left cosmos_validators_exporter_price) by (chain)",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "wallet balance, $",
   "type": "timeseries",
   "description": "Validators' wallet balance.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(cosmos_validators_exporter_wallet_balance * on (chain, denom) group_left cosmos_validators_exporter_price) by (chain)",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "total revenue, $",
   "type": "timeseries",
   "description": "Validators' rewards (self-delegated rewards + commission).",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n    cosmos_validators_exporter_unclaimed_commission\n    * on (chain, denom) group_left cosmos_validators_exporter_price\n) by (chain)\n+ sum(\n    cosmos_validators_exporter_wallet_balance\n    * on (chain, denom) group_left cosmos_validators_exporter_price\n) by (chain)\n+ sum(\n    cosmos_validators_exporter_self_delegation_rewards\n    * on (chain, denom) group_left cosmos_validators_exporter_price\n) by (chain)",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "rewards info, $",
   "type": "table",
   "description": "All info on our rewards, everything specified is in $.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cosmos_validators_exporter_supply\n* on (chain) group_left () cosmos_validators_exporter_inflation\n* on (chain, denom) group_left(address) cosmos_validators_exporter_total_delegations\n/ on (chain, denom) group_left() cosmos_validators_exporter_tokens_bonded_total\n* on (chain, address) group_left() cosmos_validators_exporter_commission\n* on (chain, denom) group_left() cosmos_validators_exporter_price\n/ 365",
     "legendFormat": "{{address}} @ {{ chain }}"
    },
    {
     "expr": "cosmos_validators_exporter_supply\n* on (chain) group_left () cosmos_validators_exporter_inflation\n* on (chain, denom) group_left(address) cosmos_validators_exporter_total_delegations\n/ on (chain, denom) group_left() cosmos_validators_exporter_tokens_bonded_total\n* on (chain, address) group_left() cosmos_validators_exporter_commission\n* on (chain, denom) group_left() cosmos_validators_exporter_price\n/ 365 * 7",
     "legendFormat": "{{address}} @ {{ chain }}"
    },
    {
     "expr": "cosmos_validators_exporter_supply\n* on (chain) group_left () cosmos_validators_exporter_inflation\n* on (chain, denom) group_left(address) cosmos_validators_exporter_total_delegations\n/ on (chain, denom) group_left() cosmos_validators_exporter_tokens_bonded_total\n* on (chain, address) group_left() cosmos_validators_exporter_commission\n* on (chain, denom) group_left() cosmos_validators_exporter_price\n/ 365 * 30",
     "legendFormat": "{{address}} @ {{ chain }}"
    },
    {
     "expr": "sum(\n    cosmos_validators_exporter_unclaimed_commission\n    * on (chain, denom) group_left cosmos_validators_exporter_price\n) by (chain, address, denom)\n+ sum(\n    cosmos_validators_exporter_wallet_balance\n    * on (chain, denom) group_left cosmos_validators_exporter_price\n) by (chain, address, denom)\n+ sum(\n    cosmos_validators_exporter_self_delegation_rewards\n    * on (chain, denom) group_left cosmos_validators_exporter_price\n) by (chain, address, denom)\n+ sum(\n    cosmos_validators_exporter_self_delegated\n    * on (chain, denom) group_left cosmos_validators_exporter_price\n) by (chain, address, denom)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    cosmos_validators_exporter_unclaimed_commission\n    * on (chain, denom) group_left cosmos_validators_exporter_price\n) by (chain, address, denom)\n+ sum(\n    cosmos_validators_exporter_wallet_balance\n    * on (chain, denom) group_left cosmos_validators_exporter_price\n) by (chain, address, denom)\n+ sum(\n    cosmos_validators_exporter_self_delegation_rewards\n    * on (chain, denom) group_left cosmos_validators_exporter_price\n) by (chain, address, denom)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    cosmos_validators_exporter_self_delegated\n    * on (chain, denom) group_left cosmos_validators_exporter_price\n) by (chain, address, denom)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rewards info, tokens",
   "type": "table",
   "description": "All info on our rewards, everything specified is in tokens.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cosmos_validators_exporter_unclaimed_commission) by (chain, address, denom)",
     "legendFormat": "{{address}} @ {{ chain }}"
    },
    {
     "expr": "sum(cosmos_validators_exporter_self_delegation_rewards) by (chain, address, denom)",
     "legendFormat": "{{address}} @ {{ chain }}"
    },
    {
     "expr": "sum(cosmos_validators_exporter_wallet_balance) by (chain, address, denom)",
     "legendFormat": "{{address}} @ {{ chain }}"
    }
   ]
  },
  { "title": "Debug info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 } },
  {
   "title": "queries failed",
   "type": "timeseries",
   "description": "Total queries amount that have failed. If some RPC is failing a lot of requests, consider switching to another one or buy a better server if it's yours.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cosmos_validators_exporter_queries_error) by (chain)",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "queries total",
   "type": "timeseries",
   "description": "Total queries done by cosmos-validators-exporter.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cosmos_validators_exporter_queries_total) by (chain)",
     "legendFormat": "{{chain}}"
    }
   ]
  }
 ]
}