{
 "title": "Slinky",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(side_car_health_check_system_updates_total,host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "healthcheck updates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(side_car_health_check_system_updates_total[$__rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "ticker updates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "rate(side_car_health_check_ticker_updates_total{host=~\"$host\"}[$__rate_interval])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "provider updates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "rate(side_car_health_check_provider_updates_total{host=~\"$host\"}[$__rate_interval])",
     "legendFormat": "{{id}}@{{provider}}: {{ success}}"
    }
   ]
  },
  { "title": "Price", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "avg price",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg(side_car_provider_price{host=~\"$host\"}) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "prices delta",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "max(side_car_provider_price{host=~\"$host\"}) by (id) - min(side_car_provider_price{host=~\"$host\"}) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "time since last price update",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - side_car_provider_last_updated_id{host=~\"$host\"}",
     "legendFormat": "{{ id }}@{{ provider }}"
    }
   ]
  },
  { "title": "HTTP responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "http responses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(side_car_api_http_status_code{host=~\"$host\"}[$__rate_interval])",
     "legendFormat": "{{ status_code_exact }}@{{provider}}"
    }
   ]
  },
  {
   "title": "ws connection status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "rate(side_car_web_socket_connection_status{host=~\"$host\"}[$__rate_interval])",
     "legendFormat": "{{status}}@{{provider}}"
    }
   ]
  },
  {
   "title": "ws handle data status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "rate(side_car_web_socket_data_handler_status{host=~\"$host\"}[$__rate_interval])",
     "legendFormat": "{{status}}@{{provider}}"
    }
   ]
  },
  {
   "title": "http 95% latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(side_car_api_response_latency_bucket{host=~\"$host\"}[$__rate_interval])) by (le, provider))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ws 95% latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(side_car_web_socket_response_time_bucket{host=~\"$host\"}[$__rate_interval])) by (le, provider))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}