{
 "title": "fullnode metrics + logs",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(cosmos_node_exporter_voting_power, host)"
    }
   },
   {
    "name": "systemd_unit",
    "label": "Systemd unit",
    "query": {}
   },
   { "name": "query" }
  ]
 },
 "panels": [
  {
   "title": "voting power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cosmos_node_exporter_voting_power{host=~\"$host\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "peers connected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{host=~\"$host\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "time since latest block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - cosmos_node_exporter_latest_block_time{host=~\"$host\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"journald\", host=~\"$host\", systemd_unit=~\"$systemd_unit\"} |~ \"$query\""
    }
   ]
  }
 ]
}