---
- name: Install node_exporter
  hosts: "{{ hosts | default('all')  }}"
  pre_tasks:
    - name: Install dependencies
      become: true
      ansible.builtin.apt:
        name: unzip
        state: latest
        update_cache: true

  roles:
    - cloudalchemy.node_exporter
