---
- name: Install Nginx and Certbot
  hosts: "{{ hosts | default('all')   }}"

  tasks:
    - name: Install nginx and snapd
      become: true
      ansible.builtin.package:
        name:
          - nginx-full
          - snapd
        state: present

    - name: Install certbot
      become: true
      community.general.snap:
        name: certbot
        classic: true
