{
 "title": "Cosmos Node Stats",
 "description": "Stats of a Cosmos fullnode",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "node catching up?",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cosmos_node_exporter_catching_up",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "time since latest block?",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cosmos_node_exporter_time_since_latest_block",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "errors?",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "1 - (cosmos_node_exporter_query_successful < 1)",
     "legendFormat": "{{ action }}@{{ host }}"
    }
   ]
  },
  {
   "title": "voting power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "cosmos_node_exporter_voting_power",
     "legendFormat": "{{ host }} "
    }
   ]
  },
  {
   "title": "mempool size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "targets": [
    { "expr": "tendermint_mempool_size", "legendFormat": "{{ chain_id }} @ {{ host  }}" }
   ]
  },
  {
   "title": "missed blocks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "rate(tendermint_consensus_validator_missed_blocks[5m])",
     "legendFormat": "{{ chain_id }} @ {{ host  }}"
    }
   ]
  },
  {
   "title": "block size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes",
     "legendFormat": "{{ chain_id }} @ {{ host  }}"
    },
    {
     "expr": "cometbft_consensus_block_size_bytes",
     "legendFormat": "{{ chain_id }} @ {{ host  }}"
    }
   ]
  },
  {
   "title": "peers connected?",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 8 },
   "targets": [
    { "expr": "tendermint_p2p_peers", "legendFormat": "{{ chain_id }} @ {{ host  }}" },
    { "expr": "cometbft_p2p_peers", "legendFormat": "{{ chain_id }} @ {{ host  }}" }
   ]
  },
  {
   "title": "versions",
   "type": "table",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "cosmos_node_exporter_local_version",
     "legendFormat": "__auto"
    },
    {
     "expr": "cosmos_node_exporter_remote_version",
     "legendFormat": "__auto"
    },
    { "expr": "cosmos_node_exporter_is_latest" }
   ]
  },
  {
   "title": "voting power %",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(cosmos_node_exporter_voting_power / on(host) group_right() tendermint_consensus_validators_power) > 0"
    },
    {
     "expr": "(cosmos_node_exporter_voting_power / on(host) group_right() cometbft_consensus_validators_power) > 0"
    }
   ]
  },
  {
   "title": "upgrades",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "cosmos_node_exporter_upgrade_estimated_time * 1000"
    },
    {
     "expr": "(cosmos_node_exporter_upgrade_estimated_time - time())"
    },
    {
     "expr": "cosmos_node_exporter_upgrade_binary_present"
    }
   ]
  },
  {
   "title": "cosmos-node-exporter info",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "targets": [
    { "expr": "cosmos_node_exporter_version" }
   ]
  }
 ]
}