{
 "title": "proxmox + vms metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "cpu usage - node_exporter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance, host) (rate(node_cpu_seconds_total{mode=\"idle\",host=~\".*proxmox.*\"}[2m])) * 100)",
     "legendFormat": "{{ device}}@{{host}}"
    }
   ]
  },
  {
   "title": "disk write - node_exporter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, host, device) (rate(node_disk_written_bytes_total{host=~\"proxmox-.*\"}[5m])) > 0",
     "legendFormat": "{{ device}}@{{host}}"
    }
   ]
  },
  {
   "title": "disk read - node_exporter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, host, device) (rate(node_disk_read_bytes_total{host=~\"proxmox-.*\"}[5m])) > 0",
     "legendFormat": "{{device}}@{{host}}"
    }
   ]
  },
  {
   "title": "cpu usage - proxmox",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio / pve_cpu_usage_limit * on (id, host) group_right pve_guest_info",
     "legendFormat": "{{name}}@{{host}}"
    }
   ]
  },
  {
   "title": "disk write - proxmox",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(pve_disk_write_bytes[5m]) * on (id, host) group_right pve_guest_info",
     "legendFormat": "{{name }}@{{node}}"
    }
   ]
  },
  {
   "title": "disk read - proxmox",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(pve_disk_read_bytes[5m]) * on (id, host) group_right pve_guest_info",
     "legendFormat": "{{name }}@{{node}}"
    }
   ]
  }
 ]
}