---
- name: Set up Loki Nginx config
  hosts: "{{ hosts | default('monitoring')  }}"

  tasks:
    - name: Install required packages
      become: true
      ansible.builtin.apt:
        name: python3-passlib
        state: latest
        update_cache: true

    - name: Add a user to a password file
      become: true
      community.general.htpasswd:
        path: /etc/loki/.htpasswd
        name: "{{ loki_username }}"
        password: "{{ loki_password }}"
        owner: loki
        group: loki
        mode: '0644'

    - name: Set up Loki Nginx template
      become: true
      ansible.builtin.template:
        src: ../../../templates/monitoring/loki-nginx.j2
        dest: /etc/nginx/sites-enabled/loki
        mode: '0644'

    - name: Generate Certbot template
      become: true
      ansible.builtin.shell: "sudo /snap/bin/certbot --nginx --agree-tos -m {{ certbot_email }} -n -d {{ loki_domain }}"
      args:
        executable: /bin/bash
      register: result
      changed_when: false

    - name: Verify Nginx config
      become: true
      ansible.builtin.command: nginx -t
      changed_when: false

    - name: (Re)start Nginx
      become: true
      ansible.builtin.systemd:
        state: restarted
        name: nginx
